version: '3.8'

services:
  ai-agent:
    build: .
    ports:
      - "8080:8080"
    environment:
      - GOOGLE_CALENDAR_API_KEY=${GOOGLE_CALENDAR_API_KEY:-}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - SERVER_PORT=8080
      - LOG_LEVEL=info
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ./logs:/app/logs
    networks:
      - ai-agent-network

networks:
  ai-agent-network:
    driver: bridge
